import platform

env = Environment()
if(platform.system() == "Linux"):
    env.Append( CPPFLAGS = '--std=c++11 -lboost_system' )

SConscript('Beast-master/include/beast/SConscript')

env.Program( source = 'main.cpp', target = 'main' )
#env.Program( source = 'Element.cpp', target = 'Element' )
#env.Program( source = 'GameBoard.cpp', target = 'GameBoard' )
